name: Building OrangeFox Recovery

on:
  workflow_dispatch:

env:
  MANIFEST: https://gitlab.com/OrangeFox/manifest.git
  BRANCH: fox_12.1
  DEVICE: RMX3761
  DT_LINK: https://github.com/SudirEbi/device_realme_RMX3761
  DT_BRANCH: twrp-omni  # Keeping the same branch
  DT_PATH: device/realme/RMX3761
  TARGET: recoveryimage
  TZ: Asia/Manila

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Free up disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android /usr/local/lib/node_modules /opt/ghc
          sudo rm -rf /usr/lib/jvm /usr/lib/llvm /usr/share/dotnet /var/lib/apt/lists/*
          docker images -q | xargs -r sudo docker rmi || true

      - name: Initialize environment
        run: |
          sudo apt-get remove account-plugin-facebook account-plugin-flickr || true
          git config --global user.name "mastersenpai05"
          git config --global user.email "pampangavergil0405@gmail.com"
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo rsync flex bison aria2 ccache
          sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+rx /usr/local/bin/repo

      - name: Sync recovery source and device tree
        run: |
          mkdir work
          cd work
          repo init -u $MANIFEST -b $BRANCH --depth=1
          repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
          git clone --depth=1 -b $DT_BRANCH $DT_LINK $DT_PATH

      - name: Build
        run: |
          cd work
          export ALLOW_MISSING_DEPENDENCIES=true
          export LC_ALL="C"
          source build/envsetup.sh
          lunch twrp_$DEVICE-eng
          mka $TARGET

      - name: Release recovery image
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: OrangeFox_12.1
          name: OrangeFox-RMX3761
          files: |
            work/out/target/product/$DEVICE/recovery.img
