name: Building TWRP 12.1 Recovery

on:
  workflow_dispatch:

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp
  BRANCH: twrp-12.1
  DEVICE: RMX3761
  DT_LINK: https://github.com/SudirEbi/vendor_realme_RMX3761
  DT_BRANCH: twrp-omni
  DT_PATH: vendor/realme/RMX3761
  TARGET: bootimage
  TZ: Asia/Manila

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Free up disk space
         run: |
            sudo apt-get clean
            sudo rm -rf /usr/local/lib/android /usr/local/lib/node_modules /opt/ghc
            sudo rm -rf /usr/lib/jvm /usr/lib/llvm /usr/share/dotnet /var/lib/apt/lists/*
            docker images -q | xargs -r sudo docker rmi || true

       - name: Initializing environment
         run: |
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker images -q | xargs -r docker rmi || true
            sudo apt-get -qq update
            sudo apt-get -qq install bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo rsync flex curl bison aria2 ccache
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo

       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST -b $BRANCH --depth=1
             repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
             git clone --depth=1 -b $DT_BRANCH $DT_LINK $DT_PATH

       - name: Build
         run: |
              cd work
              . build/envsetup.sh && lunch omni_$DEVICE-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET

       - name: Release recovery image
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: TWRP_12.1
          name: TWRP-RMX3761
          files: | 
            work/out/target/product/RMX3761/boot.img
