name: Build TWRP 12.1

on:
  workflow_dispatch:

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
  BRANCH: twrp-12.1
  DEVICE: RMX3761
  DT_LINK: https://github.com/SudirEbi/twrp_realme_RMX3761.git
  DT_BRANCH: twrp
  DT_PATH: device/realme/RMX3761
  TARGET: recoveryimage
  TZ: Asia/Manila

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
         with:
           submodules: 'recursive'

       - name: Free up disk space
         run: |
            sudo apt-get clean
            sudo rm -rf /usr/local/lib/node_modules /opt/ghc /usr/lib/jvm \
                /usr/lib/llvm /usr/share/dotnet /usr/share/man /usr/share/doc /usr/share/info \
                /usr/local/lib/python* /usr/local/cuda* /usr/lib/gcc /usr/bin \
                /var/cache/apt/* /var/lib/apt/lists/* ~/.cache
            docker system prune -af --volumes

       - name: Install dependencies
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl git wget python3 \
                gcc clang libssl-dev repo rsync flex bison aria2 ccache

       - name: Sync TWRP minimal source
         run: |
             mkdir twrp && cd twrp
             repo init -u $MANIFEST -b $BRANCH --depth=1
             repo sync -c -j4 --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune --partial-clone

       - name: Remove unneeded files to free space
         run: |
             cd twrp
             rm -rf prebuilts/ndk prebuilts/sdk prebuilts/corretto prebuilts/gcc prebuilts/gradle
             rm -rf external/chromium-trace external/perfetto external/mesa3d

       - name: Clone device and vendor trees
         run: |
             git clone --depth=1 -b twrp $DT_LINK $DT_PATH
             git clone --depth=1 -b twrp https://github.com/SudirEbi/vendor_realme_RMX3761.git vendor/realme/RMX3761

       - name: Build TWRP Recovery
         run: |
              cd twrp
              . build/envsetup.sh
              lunch twrp_$DEVICE-eng
              export ALLOW_MISSING_DEPENDENCIES=true
              mka recoveryimage -j2
             
       - name: Release TWRP recovery image
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: TWRP_12.1
          name: TWRP-RMX3761
          files: |
            twrp/out/target/product/RMX3761/recovery.img
