name: Building recovery

on:
  workflow_dispatch:

env:
  MANIFEST: https://gitlab.com/OrangeFox/sync.git
  BRANCH: fox_12.1
  DEVICE: RMX3761
  DT_LINK: https://github.com/SudirEbi/vendor_realme_RMX3761
  DT_BRANCH: twrp-omni
  DT_PATH: vendor/realme/RMX3761
  TARGET: bootimage
  TZ: Asia/Manila

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Enable Debugging
         run: set -x  # Enables debug logging

       - name: Free up disk space
         run: |
            sudo apt-get clean
            sudo rm -rf /usr/local/lib/android /usr/local/lib/node_modules /opt/ghc
            sudo rm -rf /usr/lib/jvm /usr/lib/llvm /usr/share/dotnet /var/lib/apt/lists/*
            docker images -q | xargs -r sudo docker rmi || true

       - name: Install dependencies
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo rsync flex bison aria2 ccache

       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST -b $BRANCH --depth=1
             repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
             
             echo "Listing files after repo sync:"
             ls -R
             
             git clone --depth=1 -b $DT_BRANCH $DT_LINK $DT_PATH
             
             echo "Listing files after cloning device tree:"
             ls -R $DT_PATH

       - name: Build Recovery
         run: |
              cd work
              . build/envsetup.sh
              lunch omni_$DEVICE-eng
              export ALLOW_MISSING_DEPENDENCIES=true
              mka $TARGET
             
       - name: Release recovery image
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: OrangeFox_12.1
          name: OrangeFox-RMX3761
          files: |
            work/out/target/product/RMX3761/boot.img
