name: Building recovery

on:
  workflow_dispatch:

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni -b twrp-10.0-deprecated
  DEVICE: RMX3761
  DT_LINK: https://github.com/SudirEbi/vendor_realme_RMX3761
  DT_BRANCH: twrp-omni
  DT_PATH: device/realme/RMX3761
  TARGET: bootimage
  TZ: Asia/Manila

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Free up disk space
         run: |
            sudo apt-get clean
            sudo rm -rf /usr/local/lib/android /usr/local/lib/node_modules /opt/ghc
            sudo rm -rf /usr/lib/jvm /usr/lib/llvm /usr/share/dotnet /var/lib/apt/lists/*
            docker images -q | xargs -r sudo docker rmi || true
         
       - name: Initializing environment
         run: |
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker images -q | xargs -r docker rmi || true
            sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix || true
            git config --global user.name "mastersenpai05"
            git config --global user.email "pampangavergil0405@gmail.com"         
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* || true
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo rsync flex curl bison aria2 || (sudo apt-get update && sudo apt-get -qq install bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo rsync flex curl bison aria2)
            sudo -E apt-get -qq install ccache
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1
             repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
             repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
             git clone --depth=1 -b $DT_BRANCH $DT_LINK $DT_PATH
             
       - name: Update device tree to inherit vendor
         run: |
             echo '$(call inherit-product, vendor/realme/RMX3761/device-vendor.mk)' >> $DT_PATH/omni_RMX3761.mk
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh && lunch omni_$DEVICE-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET
             
       - name: Release recovery image
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: TWRP_10.0
          name: TWRP-RMX3761
          files: | 
            work/out/target/product/RMX3761/boot.img
