name: Recovery Build

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Print Test Message
        run: echo "Workflow started successfully!"
